version: '3.1'
services:
      tomcat:
        # build:
        #   context: ./tomcat
        #   dockerfile: Dockerfile
        container_name: tomcat8
        image: tomcat

      nginx:
         # build:
          # context: ./nginx
          # dockerfile: Dockerfile
        container_name: nginx
        image: nginx
        links:
          - "tomcat"
        volumes:
          - ./proxyConf:/etc/nginx/conf.d
        depends_on: 
        - tomcat 
        ports:
          - "80:80"
          - "443:443"
